### ISSUE TITLE
Request for membership 

### ISSUE THREAD

**Issue by maiers72** [SwissAngular/members#10]
Hello everybody, 

could you please add me as member? My username is maiers72 and my twitter handle @maiers72
Kind regards 
Stephan

**Comment by damienbod** [comment]
@maiers72 
done  thanks. I sent you an invite, when you accept it set your link to public if you want the icon to appear on your profile

https://github.com/orgs/SwissAngular/people

Greetings Damien

**Comment by maiers72** [comment]
Hello Damian,

Thank you very much for adding me as member. 

Have a nice evening 
Stephan
