### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by asith-w** [SwissAngular/members#11]
Hi,  
Could you add me as member? i am not good fan of twitter.
GitHub Username : [asith-w](https://github.com/asith-w)

**Comment by FabianGosebrink** [comment]
Whats your twitter handle?

**Comment by asith-w** [comment]
Twitter handle [@Asithw](https://twitter.com/asithw)

**Comment by damienbod** [comment]
Hi @asith-w thanks

You have to accept your invitation and go to this page:

https://github.com/orgs/SwissAngular/people

And make your membership public if you want other uses to see your org.

Greetings Damien
