### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by muehan** [SwissAngular/members#33]
[github](https://github.com/muehan)
[twitter](https://twitter.com/andremuehle)

thanks!

**Comment by damienbod** [comment]
Hi @muehan thanks! Sorry with the slow answer...

You need to set your membership to pubic, if you want other people t see it on github

https://github.com/orgs/SwissAngular/people

Greetings Damien

**Comment by muehan** [comment]
sounds like a really silly question, but how can I set my membership to public?
I can not find anything like that in my profile and google does also not show me anything like that.

In Organizations I only see "You are not a member of any organizations."
